version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15
        environment:
          TZ: Asia/Tokyo

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: npm config set package-lock false && npm install
      - save_npm
      - run:
          name: Run lint
          command: npm run lint
  audit:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Run a security audit
          command: npm audit
      - run:
          name: Check for outdated packages
          command: sh .circleci/outdated.sh
          when: always

workflows:
  commit:
    jobs:
      - lint
  weekly:
    triggers:
      - schedule:
          cron: '0 0 * * 6' # Every Saturday 9:00 AM
          filters:
            branches:
              only:
                - develop
    jobs:
      - audit
