version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/node:12

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies
          key: dependencies-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: echo "package-lock=false" >> .npmrc && npm install
      - save_cache:
          name: Cache dependencies
          key: dependencies-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run lint
          command: npm run lint
  audit:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Run a security audit
          command: npm audit

workflows:
  commit:
    jobs:
      - test
  weekly:
    jobs:
      - audit
    triggers:
      - schedule:
          cron: '0 0 * * 6' # Every Saturday 9:00 AM
          filters:
            branches:
              only:
                - release
