version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15
  builder:
    working_directory: ~/project
    docker:
      - image: electronuserland/builder:wine-mono

commands:
  install_packages:
    steps:
      - restore_cache:
          name: Restore dependencies
          key: dependencies-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: echo "package-lock=false" >> .npmrc && npm install
      - save_cache:
          name: Cache dependencies
          key: dependencies-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - install_packages
      - run:
          name: Run lint
          command: npm run lint
  fordeploy:
    executor:
      name: builder
    steps:
      - checkout
      - install_packages
      - run:
          name: Build Electron application
          command: npm run build -- --linux --windows --publish always
  audit:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Run a security audit
          command: npm audit

workflows:
  commit:
    jobs:
      - test
      - fordeploy:
          requires:
            - test
          filters:
            branches:
              only:
                - release
  weekly:
    jobs:
      - audit
    triggers:
      - schedule:
          cron: '0 0 * * 6' # Every Saturday 9:00 AM
          filters:
            branches:
              only:
                - develop
