version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15
        environment:
          TZ: Asia/Tokyo

commands:
  restore_packages:
    steps:
      - restore_cache:
          name: Restore dependencies
          key: yarn-v1-{{ checksum "yarn.lock" }}
  save_packages:
    steps:
      - save_cache:
          name: Cache dependencies
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_packages
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - save_packages
      - run:
          name: Run lint
          command: npm run lint
  audit:
    executor:
      name: default
    steps:
      - checkout
      - restore_packages
      - run:
          name: Run a security audit
          command: yarn audit
      - run:
          name: Check for outdated packages
          command: sh .circleci/outdated.sh
          when: always

workflows:
  commit:
    jobs:
      - lint
  weekly:
    jobs:
      - audit
    triggers:
      - schedule:
          cron: '0 0 * * 6' # Every Saturday 9:00 AM
          filters:
            branches:
              only:
                - develop
