export const TMPFILE_OBSERVING = 'tmpfile_observing'
export const ON_MAXIMIZE = 'on-maximize'
export const ON_UNMAXIMIZE = 'on-unmaximize'
export const CONFIRM_RESTART = 'confirm-restart'
export const UPDATE_NOTIFICATION = 'update-notification'
