// Vuex用 ipcTypes.jsも同時変更が必要
export const PRELOGIN = 'prelogin'
export const CHECK_LOGIN = 'check-login'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const GET_USER_INFO = 'get-user-info'
export const GET_AUTH_EMAIL = 'show-auth-email'
export const INVITE = 'invite'
export const CHECK_WORKING_DIR = 'check-working-dir'
export const GET_WORKING_DIR = 'get-working-dir'
export const SET_WORKING_DIR = 'set-working-dir'
export const FETCH_ROOMS = 'fetch-rooms'
export const CREATE_ROOM = 'create-room'
export const FETCH_FILE = 'fetch-file'
