name: Deploy

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Set autocrlf
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Build and Deploy
        run: npm run build -- --publish always
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MOCK_ENABLED: ${{ secrets.MOCK_ENABLED }}
          S3_URL: ${{ secrets.S3_URL }}
